version: '3'

services:
  app:
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      STORAGE: 'redis'
  redis:
    image: redis